// CART TYPES

export const CART_DATA_REQUEST = "CART_DATA_REQUEST";
export const CART_DATA_RESPONSE = "CART_DATA_RESPONSE";
export const CART_DATA_FAILED = "CART_DATA_FAILED";

export const ADD_NEW_CART_REQUEST = "ADD_NEW_CART_REQUEST";
export const ADD_NEW_CART_RESPONSE = "ADD_NEW_CART_RESPONSE";
export const ADD_NEW_CART_FAILED = "ADD_NEW_CART_FAILED";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_RESPONSE = "UPDATE_CART_RESPONSE";
export const UPDATE_CART_FAILED = "UPDATE_CART_FAILED";

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const DELETE_CART_RESPONSE = "DELETE_CART_RESPONSE";
export const DELETE_CART_FAILED = "DELETE_CART_FAILED";

export const CART_DETAILS_REQUEST = "CART_DETAILS_REQUEST";
export const CART_DETAILS_RESPONSE = "CART_DETAILS_RESPONSE";
export const CART_DETAILS_FAILED = "CART_DETAILS_FAILED";


export const ADD_PACKAGE_REQUEST = "ADD_PACKAGE_REQUEST";
export const ADD_OFFERING_REQUEST = "ADD_OFFERING_REQUEST";
export const UPDATE_OFFERING_COUNT_REQUEST = "UPDATE_OFFERING_COUNT_REQUEST";
