export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_RESPONSE = "USER_DETAILS_RESPONSE"
export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED"

export const ADD_NEW_USER_DETAILS_REQUEST = "ADD_NEW_USER_DETAILS_REQUEST"
export const ADD_NEW_USER_DETAILS_RESPONSE = "ADD_NEW_USER_DETAILS_RESPONSE"
export const ADD_NEW_USER_DETAILS_FAILED = "ADD_NEW_USER_DETAILS_FAILED"

// export const PACKAGE_DETAILS_DATA_REQUEST = "PACKAGE_DETAILS_DATA_REQUEST"
// export const PACKAGE_DETAILS_DATA_RESPONSE = "PACKAGE_DETAILS_DATA_RESPONSE"
// export const PACKAGE_DETAILS_DATA_FAILED = "PACKAGE_DETAILS_DATA_FAILED"

// export const DELETE_USER_DETAILS_REQUEST = "DELETE_USER_DETAILS_REQUEST"
// export const DELETE_USER_DETAILS_RESPONSE = "DELETE_USER_DETAILS_RESPONSE"
// export const DELETE_USER_DETAILS_FAILED = "DELETE_USER_DETAILS_FAILED"

// export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST"
// export const UPDATE_USER_DETAILS_RESPONSE = "UPDATE_USER_DETAILS_RESPONSE"
// export const UPDATE_USER_DETAILS_FAILED = "UPDATE_USER_DETAILS_FAILED"